desc "Run tests"
task :test => [:testNumToRoman, :testRomanToNum]

task :testNumToRoman do
  sh ("ghc -e main fromNumToRomanTest.hs")
end

task :testRomanToNum do
  sh ("ghc -e main fromRomanToNumTest.hs")
end
